-

  name: This is my first play.
  hosts: sqlserver1
  vars:
    ansible_ssh_pass: "{{ lookup('ini','password section=sqlserver1 file=credentials.ini') }}"
  tasks:
    -

      name: "Create a dummy file on webserver1"
      command: touch /tmp/ini_lookups.txt

  

