---
  - name: This module is for creating files on remote servers.
    hosts: webservers
    become: yes
    tasks:
      - name: Remove /tmp directory.
        ansible.builtin.file:
          path: /tmp
          state: absent
      - name: Re-create /tmp directory
        ansible.builtin.file:
          path: /tmp
          state: directory
          mode: '0777'
      - name: Create a file in /tmp directory with some content on remote servers.
        lineinfile:
          path: /tmp/test.txt
          line: 'This is a test file.'
          create: yes
