-
    name: This is my first play.
    hosts: webserver1
    become: yes
    user: abhay
    connection: ssh
    tasks:
      - 
        name: "sleep for 120 sec"
        command: sleep 120
      - 
        name: "task 2"
        command: touch /tmp/second_task.txt
